# numero1 = input('Digite um nomero qualquer! ')
# numero2 = int(input('Digite um nomero qualquer! '))
# numero3 = float(input('Digite um numero qualquer! '))
# numero4 = str(input('Digite um numero qualquer! '))
# numero5 = bool(input('Digite um numero qualquer! '))
# print(type(numero1))
# print(type(numero2))
# print(type(numero3))
# print(type(numero4))
# print(type(numero5))
print("Vamos somar!")
numero1 = int(input("Digite o primeiro numero: "))
numero2 = int(input("Digite o segundo numero: "))
soma = numero1 + numero2
print("A soma entre o numero {} e {} é {}".format(numero1, numero2, soma))
