print("O desafio agora é ler a sua medida em metros e converter para centimetros e milimetros")
metros = float(input("Digite a medida em metros: "))
centimetros = int(metros * 100)
milimetros = int(centimetros * 10)
print("{} metros é igual a {} centimetros e {} milimetros.".format(metros, centimetros, milimetros))
