nome = str(input("Digite o seu nome completo: ")).strip().title()
nome = nome.split()
# print('Prazer em te conhecer, o seu primeiro nome é {}, e o seu ultimo nome é {}'.format(nome[0], nome[len(nome)-1]))
print("Muito prazer em te conhecer!")
print("Seu primeiro nome é {}".format(nome[0]))
print("Seu ultimo nome é {}".format(nome[len(nome) - 1]))
